name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install packages
        run: make install
        
      - name: Lint
        run: make lint
        
      - name: Test
        run: make test
        
      - name: Format code
        run: make format

      - name: Build package
        run: python setup.py sdist bdist_wheel  # Explicit build command to generate files in ./dist

      - name: List dist directory contents
        run: ls -l ./dist  # This step will list the files in ./dist to verify they are created

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: packaged-tool
          path: ./dist/*

      - name: Deploy
        run: make deploy  # Separate deploy step after uploading the artifact
